#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.jianghongbo.entity
  mapperLocations: classpath:mapper/*.xml

###配置打印sql
logging:
  level:
    com.jianghongbo: DEBUG #包路径为mapper文件包路径
    org.springframework.boot.autoconfigure: INFO
---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://47.98.183.208:3306/shss
    username: root
    password: Jhb123456~
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource